# Generated by Django 3.1.2 on 2021-10-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.IntegerField()),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_dob', models.DateField(blank=True, null=True)),
                ('student_doj', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
