# Generated by Django 3.1.2 on 2021-10-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
